// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package sqlc

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Account struct {
	LabID        string       `json:"lab_id"`
	Labname      string       `json:"labname"`
	Email        string       `json:"email"`
	PasswordHash string       `json:"password_hash"`
	CreatedAt    sql.NullTime `json:"created_at"`
}

type Attendance struct {
	LabSessionID string        `json:"lab_session_id"`
	IpAddress    string        `json:"ip_address"`
	MacAddress   string        `json:"mac_address"`
	Fall         sql.NullInt32 `json:"fall"`
	Gas          sql.NullInt32 `json:"gas"`
}

type Fallga struct {
	Fall sql.NullInt32 `json:"fall"`
	Gas  sql.NullInt32 `json:"gas"`
}

type Labsession struct {
	LabSessionID string         `json:"lab_session_id"`
	LabID        sql.NullString `json:"lab_id"`
	Pic          sql.NullString `json:"pic"`
	ModuleTopic  sql.NullString `json:"module_topic"`
	StartTime    sql.NullTime   `json:"start_time"`
	EndTime      sql.NullTime   `json:"end_time"`
	Location     sql.NullString `json:"location"`
	Attendance   sql.NullInt32  `json:"attendance"`
	Indicator    sql.NullString `json:"indicator"`
}

type Logging struct {
	LabSessionID sql.NullString `json:"lab_session_id"`
	TimeLog      sql.NullTime   `json:"time_log"`
	IpAddress    sql.NullString `json:"ip_address"`
	Report       sql.NullString `json:"report"`
}

type Session struct {
	ID           uuid.UUID `json:"id"`
	LabID        string    `json:"lab_id"`
	Labname      string    `json:"labname"`
	RefreshToken string    `json:"refresh_token"`
	IsBlocked    bool      `json:"is_blocked"`
	ExpiresAt    time.Time `json:"expires_at"`
	CreatedAt    time.Time `json:"created_at"`
}
